import { useEffect, useRef, useState } from 'react';
import { api } from './api.js';
import { overviewMoney as money, overviewDate as date } from './receiptsOverviewState.js';
export default function OverviewStatement({ onClose, onConfirmed }) {
  const [file,setFile]=useState(null), [preview,setPreview]=useState(null), [busy,setBusy]=useState(false), [error,setError]=useState(''), [saved,setSaved]=useState(null);
  const [imports,setImports]=useState([]), [confirmed,setConfirmed]=useState(null);
  useEffect(()=>{api.inboxImports().then(rows=>setImports(rows.filter(r=>r.provider==='OVERVIEW_STATEMENT'))).catch(e=>setError(e.message));},[]);
  const openSaved=async id=>{setBusy(true);setError('');setConfirmed(null);try{const result=await api.savedOverviewStatement(id);setPreview(result);setSaved(result);setFile(null);}catch(e){setError(e.message);}finally{setBusy(false);}};
  const confirm=async()=>{setBusy(true);setError('');try{const result=await api.confirmOverviewStatement(saved.id,preview.confirmation_token);setConfirmed(result);setPreview(await api.savedOverviewStatement(saved.id));setImports((await api.inboxImports()).filter(r=>r.provider==='OVERVIEW_STATEMENT'));onConfirmed?.();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const panel=useRef(null);
  useEffect(()=>{const previous=document.activeElement;panel.current?.focus();return()=>previous?.focus();},[]);
  const run=async save=>{setBusy(true);setError('');try{const result=await api.overviewStatement(file,save);setPreview(result);if(save){setSaved(result);setPreview(await api.savedOverviewStatement(result.id));setImports((await api.inboxImports()).filter(r=>r.provider==='OVERVIEW_STATEMENT'));}}catch(e){if(!e.authExpired)setError(e.message);}finally{setBusy(false);}};
  const readyRows=(preview?.confirmations||[]).filter(r=>!r.already_confirmed);
  const doneRows=(preview?.confirmations||[]).filter(r=>r.already_confirmed);
  const readyTotal=readyRows.reduce((n,r)=>n+Number(r.amount||0),0);
  const doneTotal=doneRows.reduce((n,r)=>n+Number(r.amount||0),0);
  const step=confirmed?4:saved?3:preview?2:1;
  const steps=['เลือกไฟล์','ตรวจบัญชีและยอดรวม','ตรวจผลจับคู่','ยืนยัน'];
  return <div className="ro-modal-backdrop"><section className="ro-statement" role="dialog" aria-modal="true" aria-label="นำเข้า / ตรวจ Statement" tabIndex={-1} ref={panel} onKeyDown={e=>{
    if(e.key==='Escape'&&!busy)onClose();
    if(e.key==='Tab'){const nodes=[...panel.current.querySelectorAll('button:not([disabled]), input:not([disabled]), select:not([disabled]), summary')];if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}
  }}>
    <header><div><h2>นำเข้า / ตรวจ Statement</h2><p>ตรวจเงินเข้า QR กสิกร / GRAB food จาก CSV ธนาคาร</p></div><button disabled={busy} onClick={onClose} aria-label="ปิดนำเข้า Statement">ปิด</button></header>
    <ol className="ro-steps" aria-label="ขั้นตอนตรวจ Statement">{steps.map((s,i)=><li key={s} className={i+1<step?'done':i+1===step?'current':''} aria-current={i+1===step?'step':undefined}><span>{i+1}</span>{s}</li>)}</ol>
    <p>ระบบอ่านรายการเงินเข้าและแยกประเภทตามรายละเอียดธนาคาร แสดงตามวันที่เงินเข้าในไฟล์ ครอบคลุมทั้งไฟล์โดยไม่ใช้ตัวกรองหน้าสรุป</p>
    <section aria-label="ขั้นตอนที่ 1 เลือกไฟล์"><h3>1 · เลือกไฟล์</h3>
    <label>ไฟล์ที่แนบไว้แล้ว<select aria-label="เลือก Statement ที่บันทึกไว้" disabled={busy} value={saved?.id||''} onChange={e=>e.target.value&&openSaved(e.target.value)}><option value="">เลือกไฟล์เดิม ไม่ต้องแนบซ้ำ</option>{imports.map(i=><option key={i.id} value={i.id}>{i.original_name} · {i.status}</option>)}</select></label>
    <label>ไฟล์ Statement กสิกร (.csv)<input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{setFile(e.target.files[0]||null);setPreview(null);setSaved(null);setConfirmed(null);setError('');}}/></label>
    <button className="ro-primary" disabled={!file||busy} onClick={()=>run(false)}>{busy?'กำลังตรวจ…':'ตรวจไฟล์'}</button>
    {error&&<p className="ro-error" role="alert">{error}</p>}</section>
    {preview?.validation&&<section className={`ro-account-verification ${preview.validation.can_confirm?'matched':'unmatched'}`} aria-label="ขั้นตอนที่ 2 ผลตรวจตามเงื่อนไขระบบ"><h3>2 · {preview.validation.can_confirm?'ผ่านการตรวจความครบถ้วนของไฟล์':'ห้ามยืนยัน — ไฟล์ยังไม่ผ่านการตรวจ'}</h3><p>ไฟล์ผ่านยังต้องจับคู่แต่ละรายการให้ครบก่อนยืนยัน รายการไม่ทราบประเภทหรือจับคู่ไม่ชัดจะยังรอตรวจ</p><details><summary>ดูรายละเอียดการตรวจ</summary><div className="ro-detail-table"><table><thead><tr><th>เงื่อนไข</th><th>ผล</th><th>รายละเอียด</th></tr></thead><tbody>{preview.validation.rules.map(r=><tr key={r.id}><td>{r.label}</td><td>{r.status==='PASS'?'ผ่าน':'ห้ามยืนยัน'}</td><td>{r.detail}</td></tr>)}</tbody></table></div><ul><li>QR: รหัสร้านหลักต้องตรงกับสาขาและวันของเอกสาร รหัสรองต้องมีหลักฐานการตรวจเดิม</li><li>Grab: ตรวจชื่อผู้โอนและ X3812 เทียบยอดสุทธิรายงานของแต่ละสาขาในวันขายก่อนวันรับหนึ่งวัน ต้องตรงถึงสตางค์และมีคู่เดียว</li><li>Grab ที่อ่านเก็บไว้เป็นศูนย์: อ่าน PDF ต้นฉบับใหม่ ตรวจวันขายและรหัสร้านก่อนใช้ยอด</li><li>บัตรกสิกร: ใช้หลักฐานเดิมที่ตรงบัญชี วันเงินเข้า ยอด และรายละเอียด ไม่เดาวันขาย</li><li>รายการเดิมที่ยืนยันแล้วไม่เพิ่มเงินซ้ำ รายการที่ข้อมูลเปลี่ยนต้องเปิดตรวจใหม่ก่อนยืนยัน</li><li>เงินไม่ทราบประเภทและผู้โอน Grab ไม่ตรง: ต้องตรวจเพิ่ม ไม่จัดเป็นยอดขายเอง</li><li>รายการเหมือนกันในไฟล์: ระงับจับคู่อัตโนมัติจนกว่าจะตรวจเลขอ้างอิง</li><li>ยอดเกินสามเท่าของค่ากลางในช่องทางเดียวกัน เมื่อมีอย่างน้อยห้ารายการ: แจ้งให้ตรวจเพิ่ม ไม่สรุปว่าเงินผิด</li><li>ยืนยันแล้วเก็บไฟล์ต้นฉบับ ผู้ยืนยัน และประวัติ เอกสารปิดแล้วคงยอดปิดเดิมไว้</li></ul></details></section>}
    {preview&&<><section className={`ro-account-verification ${preview.verification.status==='MATCHED'?'matched':'unmatched'}`} aria-label="บัญชีรับเงิน">
      <h3>{preview.verification.status==='MATCHED'?'✓ ยืนยันบัญชีตรงกับระบบ':'ยังยืนยันบัญชีไม่ได้'}</h3>
      <p><strong>ธนาคารกสิกรไทย · {preview.verification.number?.replace(/^(\d{3})(\d)(\d{5})(\d)$/,'$1-$2-$3-$4')||'อ่านเลขบัญชีไม่พบ'}</strong></p>
      {preview.verification.account?<><p>ชื่อบัญชี: {preview.verification.account.name||'ยังไม่ระบุ'} · {preview.verification.account.label}</p><p>สาขาที่ตั้งไว้: {preview.verification.account.branch||'บัญชีกลาง'}</p><small>ตรวจเลขบัญชีเต็มจากหัว Statement ตรงกับบัญชีรับเงินในระบบ{preview.verification.account.additional_route_keys.some(key=>key.split(':')[0]!==String(preview.verification.account.branch_id))?' · บัญชีนี้มีเส้นทางรับเงินหลายสาขา ต้องจับคู่สาขาของแต่ละรายการต่อ':''}</small></>:<p>{preview.verification.status==='AMBIGUOUS'?'พบเลขบัญชีซ้ำในตั้งค่า กรุณาตรวจสอบก่อนบันทึก':'ไม่พบเลขบัญชีนี้ในบัญชีกสิกรที่เปิดใช้งาน กรุณาตรวจบัญชีในหน้าตั้งค่า'}</p>}
    </section><div className="ro-detail-totals">{['QR กสิกร','GRAB food','บัตรกสิกร','เงินเข้าอื่น · ต้องตรวจ'].map(channel=><div className="ro-metric" key={channel}><span>{channel}</span><strong>{money(preview.rows.filter(r=>r.channel===channel).reduce((n,r)=>n+Number(r.amount),0))}</strong><small>{preview.rows.filter(r=>r.channel===channel).length} รายการ</small></div>)}</div>
    <p><strong>เงินเข้ารวม {money(preview.total)} บาท · {preview.count} รายการ</strong></p>
    {preview.grab&&<p><strong>ตรวจ Grab: {preview.grab.count?`${preview.grab.count} รายการ · ${money(preview.grab.total)} บาท`:'ไม่พบเงินเข้าที่ระบุผู้โอนเป็น Grab ในไฟล์นี้'}</strong><br/>{preview.grab.note} · การไม่พบรายการในบัญชีนี้ยังไม่ถือว่าเงินขาด</p>}
    {saved&&preview.confirmations&&<section className="ro-account-verification" aria-label="ขั้นตอนที่ 3 ผลจับคู่"><h3>3 · ตรวจผลจับคู่</h3>
      {!!readyRows.length&&<><h4>พร้อมยืนยัน {readyRows.length} รายการ · {money(readyTotal)} บาท</h4><p>เอกสารปิดแล้วจะเพิ่มหลักฐานรับเงินจริงและประวัติ โดยเก็บยอดปิดเอกสารเดิมไว้</p><div className="ro-detail-table"><table><thead><tr><th>วันขาย / วันรับ</th><th>สาขา / ช่องทาง</th><th>เงินรับ</th></tr></thead><tbody>{readyRows.map(r=><tr key={r.row_index}><td>{date(r.sale_date)} / {date(r.date)}</td><td>{r.branch_name} · {r.channel}</td><td>{money(r.amount)}</td></tr>)}</tbody></table></div></>}
      {!!doneRows.length&&<details><summary>ยืนยันไว้แล้ว {doneRows.length} รายการ · {money(doneTotal)} บาท</summary><div className="ro-detail-table"><table><thead><tr><th>วันขาย / วันรับ</th><th>สาขา / ช่องทาง</th><th>เงินรับ</th></tr></thead><tbody>{doneRows.map(r=><tr key={r.row_index}><td>{date(r.sale_date)} / {date(r.date)}</td><td>{r.branch_name} · {r.channel}</td><td>{money(r.amount)}</td></tr>)}</tbody></table></div></details>}
      {!!preview.unmatched?.length&&<><h4>ต้องตรวจเพิ่ม {preview.unmatched.length} รายการ</h4><div className="ro-detail-table"><table><thead><tr><th>วันที่</th><th>ช่องทาง</th><th>ยอด</th><th>เหตุผลและสิ่งที่ต้องทำต่อ</th></tr></thead><tbody>{preview.unmatched.map(r=><tr key={r.row_index}><td>{date(r.date)}</td><td>{r.channel}</td><td>{money(r.amount)}</td><td>{r.pending_reason}</td></tr>)}</tbody></table></div></>}
    </section>}
    <details><summary>ดูยอดรายวันและรายละเอียดแยกสาขา Grab</summary>
    {!!preview.grab?.allocations?.length&&<section className="ro-account-verification"><h3>แยก Grab ตามสาขาจากรายงานอัตโนมัติ</h3><p>ใช้ยอดสุทธิในรายงาน Grab เทียบเงินเข้าของวันถัดไป ไม่ใช้สาขาเจ้าของบัญชีหรือเรียงลำดับเวลาโอน</p>
      <div className="ro-detail-totals">{preview.grab.branches.map(b=><div className="ro-metric" key={b.code}><span>{b.name}</span><strong>{money(b.total)}</strong><small>{b.count} รายการ</small></div>)}<div className="ro-metric"><span>รอแยกสาขา</span><strong>{money(preview.grab.pending_total)}</strong><small>{preview.grab.pending_count} รายการ</small></div></div>
      <div className="ro-detail-table"><table><thead><tr><th>วันเงินเข้า</th><th>วันขายอ้างอิง</th><th>สาขา</th><th>ยอด</th><th>ผลจับคู่</th></tr></thead><tbody>{preview.grab.allocations.map(r=><tr key={r.row_index}><td>{date(r.received_date)}</td><td>{date(r.sale_date)}</td><td>{r.branch_name||'รอจับคู่'}</td><td>{money(r.amount)}</td><td>{r.reason}</td></tr>)}</tbody></table></div></section>}
    <p className="ro-reasons">การยืนยันบัญชีรับเงินแยกจากการจับคู่วันขายและสาขาของแต่ละรายการ ต้องจับคู่ต่อก่อนเปลี่ยน “รับที่ยืนยัน”</p>
    <div className="ro-detail-table"><table><thead><tr><th>วันที่รับเงินจริง</th><th>ประเภทที่ตรวจพบ</th><th>จำนวนรายการ</th><th>เงินเข้า</th></tr></thead><tbody>{preview.daily.map(r=><tr key={r.date+r.channel}><td>{date(r.date)}</td><td>{r.channel}</td><td>{r.count}</td><td>{money(r.amount)}</td></tr>)}</tbody></table></div>
    </details>
    {preview.alerts&&<section className="ro-account-verification unmatched" aria-label="รายการเงินเข้าต้องตรวจ">
      <h3>{preview.alerts.length?`พบเงินเข้าที่ต้องตรวจ ${preview.alerts.length} รายการ`:'ไม่พบจุดเตือนตามกติกาที่ตรวจในไฟล์นี้'}</h3>
      <p>ตรวจเงินเข้าที่ไม่ทราบประเภท ข้อมูลผู้โอน Grab ไม่ตรง รายการอาจซ้ำ และยอดสูงกว่าค่ากลางเกิน 3 เท่าเมื่อมีอย่างน้อย 5 รายการในช่องทางเดียวกัน</p>
      {!!preview.alerts.length&&<div className="ro-detail-table"><table><thead><tr><th>วันรับ / รายการ</th><th>เงินเข้า</th><th>เหตุผลที่ต้องตรวจ</th><th>รายละเอียดธนาคาร</th></tr></thead><tbody>{preview.alerts.map(r=><tr key={r.row_index}><td>{date(r.date)}<br/>รายการ {r.row_index}</td><td>{money(r.amount)}</td><td>{r.reasons.join(' · ')}</td><td>{r.description}</td></tr>)}</tbody></table></div>}
    </section>}
    <details><summary>รายละเอียดจากธนาคารทั้งหมด</summary><div className="ro-detail-table"><table><thead><tr><th>วันที่</th><th>รายละเอียด</th><th>ยอด</th></tr></thead><tbody>{preview.rows.map((r,i)=><tr key={i}><td>{date(r.date)}</td><td>{r.description}</td><td>{money(r.amount)}</td></tr>)}</tbody></table></div></details>
    {saved&&preview.confirmations&&<section className="ro-account-verification" aria-label="ขั้นตอนที่ 4 ยืนยัน"><h3>4 · ยืนยัน {readyRows.length} รายการ · {money(readyTotal)} บาท</h3><button className="ro-primary" disabled={busy||!preview.confirmable_count} onClick={confirm}>ยืนยันรับเงินตามหลักฐาน</button>{confirmed&&<p role="status">ยืนยันแล้ว {confirmed.confirmed_count} รายการ หน้าสรุปอัปเดตแล้ว · รอจับคู่ {confirmed.unmatched_count} รายการ</p>}</section>}
    {saved?<p role="status">{saved.duplicate?'มีไฟล์นี้ในระบบแล้ว':'บันทึกหลักฐานแล้ว'} · เลขที่ {saved.id} · เปิดไฟล์ต่อได้ในหน้าไฟล์อีเมล</p>:<button className="ro-primary" disabled={busy||!preview.validation?.can_confirm} onClick={()=>run(true)}>บันทึกหลักฐานไว้รอจับคู่</button>}
    </>}
  </section></div>;
}
