import RecurringExpenses from './RecurringExpenses.jsx';
import { useEffect, useRef, useState } from 'react';
import { request } from './api.js';
import { formatPnlMoney as money, sumPnlRows, thaiMonth, previousMonth, formatPnlDateTime, pnlView, formatPnlMonth, periodMonthBounds, formatPnlDate, waitingPnlItems, isZeroPnlCategory, visiblePnlColumns, pnlApproximateSources } from './profitLoss.js';
import './profitLoss.css';
const send = (method, path, body) => request(`/pnl${path}`, { method, headers: { 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined });
const errorText = (error) => ({
  STAFF_FROM_HRMS: 'เงินเดือนต้องมาจาก HRMS ไม่สามารถตั้งเป็นรายจ่ายประจำ', RECURRING_START_OUT_OF_RANGE: 'เริ่มเดือนได้ไม่เกิน 12 เดือนก่อนหรือหลังเดือนปัจจุบัน', RECURRING_EFFECTIVE_OUT_OF_RANGE: 'เดือนที่มีผลต้องอยู่ในช่วงของเวอร์ชันที่เลือก', RECURRING_LAST_OUT_OF_RANGE: 'เดือนสุดท้ายต้องอยู่ในช่วงของเวอร์ชันที่เลือก', INVALID_TEXT: 'กรุณากรอกข้อความให้ครบและไม่เกินความยาวที่กำหนด',
  PNL_NOT_CONFIGURED: 'ยังไม่ได้ตั้งค่าการเชื่อม LINE Bill', PNL_SYNC_RUNNING: 'กำลังดึงข้อมูลอยู่ โปรดลองอีกครั้ง',
  LBC_EXPORT_V2_REQUIRED: 'LINE Bill ต้องอัปเดตระบบส่งออกก่อน', INVALID_AMOUNT: 'ยอดต้องมากกว่า 0 และมีทศนิยมไม่เกิน 2 ตำแหน่ง',
  INVALID_PERIOD_MONTH: 'เดือนของค่าใช้จ่ายต้องไม่เกินเดือนที่จ่ายจริง และย้อนหลังได้ไม่เกิน 3 เดือน', INVALID_MONTH: 'เดือนไม่ถูกต้อง', RULE_EXISTS: 'มีกฎนี้แล้ว'
}[error.details?.code] || 'ดำเนินการไม่สำเร็จ โปรดลองอีกครั้ง');
const emptyForm = () => ({ category_code: '', branch_id: '', description: '', amount: '', note: '' });
export default function ProfitLoss({ branches }) {
  const [month, setMonth] = useState(thaiMonth); const [branchId, setBranchId] = useState('');
  const [mode, setMode] = useState('matched');
  const [waitingSearch, setWaitingSearch] = useState(''); const [showAllWaiting, setShowAllWaiting] = useState(false); const [showZero, setShowZero] = useState(false);
  const [report, setReport] = useState(null); const [error, setError] = useState('');
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState(null); const [rules, setRules] = useState([]);
  const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(null); const [copies, setCopies] = useState([]);
  const generation = useRef(0);
  const reload = async () => {
    const current = ++generation.current; setLoading(true); setError('');
    try {
      const [data, ruleRows] = await Promise.all([request(`/pnl/report?${new URLSearchParams({ month, branch_id: branchId })}`), request('/pnl/rules')]);
      if (current === generation.current) { setReport(data); setRules(ruleRows); }
    } catch (err) { if (current === generation.current) { setError(errorText(err)); setReport(null); } }
    finally { if (current === generation.current) setLoading(false); }
  };
  useEffect(() => { setReport(null); setSelected(null); setWaitingSearch(''); setShowAllWaiting(false); setShowZero(false); setCopies([]); setForm(emptyForm()); setEditing(null); reload(); return () => { generation.current++; }; }, [month, branchId]);
  const act = async (fn, refresh = true) => { setBusy(true); setError(''); try { await fn(); if (refresh) await reload(); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } };
  const categories = report?.category_rows.filter((row) => row.code !== 'UNCATEGORIZED') || [];
  const categoryOptions = <><option value="">เลือกหมวด</option>{categories.map((row) => <option key={row.code} value={row.code}>{row.name}</option>)}</>;
  const branchOptions = <><option value="">ส่วนกลาง</option>{branches.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</>;
  const view = report ? pnlView(report, mode) : null;
  const totals = view?.totals;
  const waiting = report?.items.filter((row) => !row.excluded && !row.category_code) || [];
  const suggestions = report?.items.filter((item) => !item.excluded && item.suggested_period_month && item.suggested_period_month !== item.period_month) || [];
  const excluded = report?.items.filter((row) => row.excluded) || [];
  const filtered = selected === 'REVENUE' ? [] : selected === 'EXCLUDED' ? excluded : report?.items.filter((row) => !row.excluded && (selected === 'COGS' ? categories.find((category) => category.code === row.category_code)?.is_cogs : selected === 'OPEX' ? !categories.find((category) => category.code === row.category_code)?.is_cogs : (row.category_code || 'UNCATEGORIZED') === selected)) || [];
  const selectedManual = report?.manual_expenses.filter((row) => selected === 'COGS' ? categories.find((category) => category.code === row.category_code)?.is_cogs : selected === 'OPEX' ? !categories.find((category) => category.code === row.category_code)?.is_cogs : row.category_code === selected) || [];
  const selectedRecurring = (report?.recurring?.items || []).filter((item) => !item.skipped && (selected === 'COGS' ? categories.find((row) => row.code === item.category_code)?.is_cogs : selected === 'OPEX' ? !categories.find((row) => row.code === item.category_code)?.is_cogs : item.category_code === selected));
  const selectedHrms = [...(report?.hrms_expenses || []), ...(report?.cashflow_expenses || [])].filter((item) => selected === 'OPEX' || selected === item.category_code);
  const waitingView = waitingPnlItems(waiting, waitingSearch, showAllWaiting);
  const columns = view ? visiblePnlColumns(view) : [];
  const zeroCategories = view?.category_rows.filter(isZeroPnlCategory) || [];
  const approximate = report && mode === 'matched' ? pnlApproximateSources(report) : [];
  const hasApprox = (code, bucket) => approximate.some((item) => {
    const itemBucket = item.bucket || (item.branch_id == null ? (item.manual || item.recurring ? 'CENTRAL' : 'UNASSIGNED') : String(item.branch_id));
    const isCogs = categories.find((category) => category.code === item.category_code)?.is_cogs;
    return (bucket == null || itemBucket === bucket) && (code === 'COGS' || code === 'gross_profit' ? isCogs : code === 'OPEX' ? !isCogs : code === 'net_profit' ? true : (item.category_code || 'UNCATEGORIZED') === code);
  });
  const amountText = (value, code, bucket) => `${hasApprox(code, bucket) ? '≈ ' : ''}${money(value)}`;
  const renderItems = (items) => <div className="pnl-expenses"><div className="pnl-expense-heading" aria-hidden="true"><span>วันที่ / ร้าน</span><span>รายละเอียด / ประเภท</span><span>ยอด (บาท)</span><span>จัดหมวด</span><span>จัดการ</span></div>{items.map((item) => <ExpenseRow key={item.stable_key} item={item} categories={categories} busy={busy} onSave={(body) => act(() => send('PUT', `/items/${encodeURIComponent(item.stable_key)}/override`, body))} />)}{items.length === 0 && <p>ไม่มีรายการ</p>}</div>;
  const row = (name, value, key, branchField) => <tr key={key || name} className={!key ? 'pnl-total-row' : ''}><th scope="row">{key ? <button className="pnl-link" onClick={() => setSelected(key)}>{name}</button> : name}</th><td className={value < 0 ? 'pnl-negative' : ''}>{amountText(value, key || branchField)}</td>{!branchId && columns.map((branch) => <td key={branch.key} className={branch[branchField] < 0 ? 'pnl-negative' : ''}>{amountText(branch[branchField], key || branchField, branch.key)}</td>)}</tr>;
  return <main className="pnl-page">
    <p className="pnl-notice">ตัวเลขบริหารโดยประมาณ ไม่ใช่งบการเงินหรือแบบภาษี · ยอดรวม VAT</p>
    <div className="pnl-toolbar"><h1>กำไรขาดทุน</h1><label>ช่วงข้อมูล<select value={mode} onChange={(e) => setMode(e.target.value)}><option value="month">ทั้งเดือน</option><option value="matched">เฉพาะวันที่ข้อมูลครบ</option></select></label><label>เดือน<input type="month" value={month} onChange={(e) => setMonth(e.target.value)} disabled={busy}/></label><label>สาขา<select value={branchId} onChange={(e) => setBranchId(e.target.value)} disabled={busy}><option value="">ทั้งหมด</option>{branches.map((branch) => <option value={branch.id} key={branch.id}>{branch.name}</option>)}</select></label><button disabled={busy || loading || !report?.configured} onClick={() => act(() => send('POST', '/sync', { month }))}>{busy ? 'กำลังดำเนินการ…' : 'ดึงรายจ่ายล่าสุด'}</button></div>
    {report && <p>{!report.configured ? 'ยังไม่ได้ตั้งค่าการเชื่อม LINE Bill · ' : ''}ดึงล่าสุด: {report.latest_sync ? `${formatPnlDateTime(report.latest_sync.finished_at || report.latest_sync.started_at)} · ${{SUCCEEDED:'สำเร็จ',FAILED:'ไม่สำเร็จ',RUNNING:'กำลังดึง'}[report.latest_sync.status]}${report.latest_sync.error_code ? ' · ต้องตรวจการเชื่อมต่อ' : ''}` : 'ยังไม่เคยดึงข้อมูล'}</p>}
    {error && <p role="alert" className="pnl-negative">{error}</p>}
    {loading ? <p role="status">กำลังโหลด…</p> : report && <>
      <div className="pnl-cards">{[['รายรับ', totals.revenue], ['ต้นทุนวัตถุดิบ', totals.cogs], ['ค่าใช้จ่ายอื่น', totals.opex], ['กำไรสุทธิ', totals.net_profit]].map(([label, value]) => <article key={label}><span>{label}</span><strong className={value < 0 ? 'pnl-negative' : label === 'กำไรสุทธิ' && value > 0 ? 'pnl-positive' : ''}>{label !== 'รายรับ' && hasApprox(label === 'ต้นทุนวัตถุดิบ' ? 'COGS' : label === 'ค่าใช้จ่ายอื่น' ? 'OPEX' : 'net_profit') ? '≈ ' : ''}{money(value)} <span>บาท</span></strong>{label === 'กำไรสุทธิ' && <small>อัตรากำไร {totals.margin_pct == null ? '—' : totals.margin_pct.toFixed(2) + '%'}</small>}{label === 'กำไรสุทธิ' && (mode === 'matched' ? <small>ข้อมูลครบ {report.matched_days} วัน · ดูหมายเหตุใต้ตาราง</small> : report.expense_missing_revenue_days > 0 && <small className="pnl-warning">รายจ่ายยังไม่ครบ {report.expense_missing_revenue_days} วัน — กำไรสูงเกินจริง</small>)}</article>)}</div>
      {mode === 'matched' && <p>ไม่รวมรายการไม่ระบุสาขา {money(report.matched_unassigned_excluded_total)} บาท · แต่ละสาขาคิดตามวันที่ครบของสาขานั้น; รายจ่ายประจำและกรอกเองส่วนกลางเฉลี่ยตามวันที่ทุกสาขาครบพร้อมกัน; HRMS นับเต็มเดือน</p>}
      <section className="pnl-completeness"><h2>ความครบของข้อมูล</h2>{report.completeness.map((branch) => <details key={branch.branch_id}><summary>{branch.name}: มีข้อมูลรายรับ {branch.revenue_available_days}/{branch.days_expected} วัน · ใบรับเงินปิด {branch.revenue_days}/{branch.days_expected} วัน · รายจ่าย LINE ปิดรอบ {branch.expense_days}/{branch.days_expected} วัน · ข้อมูลครบตรงกัน {branch.matched_days} วัน {branch.month_close_revision && `· ปิดเดือนแล้ว (rev ${branch.month_close_revision})`}</summary><p>รายรับยังไม่มีข้อมูล: {branch.revenue_unavailable.join(', ') || 'ไม่มี'}</p><p>เสริม POS แต่ยังไม่มีใบรับเงิน: {branch.pos_without_receipt_dates.join(', ') || 'ไม่มี'}</p><p>ใบรับเงินยังไม่ปิด: {branch.revenue_missing.join(', ') || 'ไม่มี'}</p><p>รายจ่ายยังไม่ปิดหรือไม่มีรอบ: {branch.expense_missing.join(', ') || 'ไม่มี'}</p></details>)}</section>
      <p>วัตถุดิบเป็นยอดซื้อ ยังไม่คิดสต็อก · รายจ่ายจาก HRMS ดึงแยก · รายจ่ายจากใบรับเงินดึงแยก · รายจ่ายนอกแหล่งที่เชื่อมต้องกรอกเอง · รายรับอาจเปลี่ยนเมื่อ POS แก้ย้อนหลัง</p>
      {(report.reimbursement_count + report.incoming_transfer_count > 0) && <p>มีรายการคืนเงิน/เงินเข้า {report.reimbursement_count + report.incoming_transfer_count} รายการ ไม่ได้นับ</p>}
      <section className="pnl-statement"><h2>ตารางกำไรขาดทุน</h2><div className="pnl-table-scroll" tabIndex="0" role="region" aria-label="ตารางกำไรขาดทุน เลื่อนแนวนอนได้"><table><thead><tr><th>รายการ</th><th>ยอดรวม (บาท)</th>{!branchId && columns.map((branch) => <th key={branch.key}>{branch.name}</th>)}</tr></thead><tbody>
        {row('รายรับ', totals.revenue, 'REVENUE', 'revenue')}{row('ต้นทุนวัตถุดิบ', totals.cogs, 'COGS', 'cogs')}{row('กำไรขั้นต้นโดยประมาณ', totals.gross_profit, null, 'gross_profit')}
        {view.category_rows.filter((category) => showZero || !isZeroPnlCategory(category)).map((category) => <tr key={category.code}><th scope="row"><button className="pnl-link" onClick={() => setSelected(category.code)}>{category.name}{category.is_cogs ? ' (ต้นทุนวัตถุดิบ)' : ''}</button></th><td className={category.amount < 0 ? 'pnl-negative' : ''}>{amountText(category.amount, category.code)}</td>{!branchId && columns.map((branch) => <td key={branch.key} className={category.branches[branch.key] < 0 ? 'pnl-negative' : ''}>{amountText(category.branches[branch.key], category.code, branch.key)}</td>)}</tr>)}
        {zeroCategories.length > 0 && <tr><th colSpan={branchId ? 2 : columns.length + 2}><button className="pnl-link" aria-expanded={showZero} onClick={() => setShowZero(!showZero)}>{showZero ? 'ซ่อนหมวดที่ไม่มีรายการ' : 'หมวดที่ไม่มีรายการ'} ({zeroCategories.length})</button></th></tr>}
        {row('กำไรสุทธิโดยประมาณ', totals.net_profit, null, 'net_profit')}
      </tbody></table></div>{mode === 'matched' && <p className="pnl-footnote">≈ รวมรายจ่ายรายเดือนที่เฉลี่ยตาม {report.matched_days}/{new Date(Date.UTC(Number(report.month.slice(0, 4)), Number(report.month.slice(5)), 0)).getUTCDate()} วันที่ข้อมูลครบ · แต่ละสาขาใช้จำนวนวันที่ครบของสาขานั้น · ส่วนกลางใช้วันที่ทุกสาขาครบพร้อมกัน · HRMS นับเต็มเดือน</p>}</section>
      {selected && <section><h2>รายการ: {selected === 'REVENUE' ? 'รายรับ POS' : selected === 'COGS' ? 'ต้นทุนวัตถุดิบ' : selected === 'OPEX' ? 'ค่าใช้จ่ายอื่น' : selected === 'EXCLUDED' ? 'ไม่นับเป็นค่าใช้จ่าย' : report.category_rows.find((row) => row.code === selected)?.name}</h2><button onClick={() => setSelected(null)}>ปิดรายการ</button>{selected === 'REVENUE' ? <div className="pnl-table-scroll"><table><thead><tr><th>วันที่</th><th>สาขา</th><th>ยอด POS รวม VAT</th><th>สถานะ</th></tr></thead><tbody>{[...report.revenue_receipts, ...report.revenue_pos_without_receipt].sort((a, b) => a.receipt_date.localeCompare(b.receipt_date) || Number(a.branch_id) - Number(b.branch_id)).map((receipt) => <tr key={receipt.id || `pos:${receipt.branch_id}:${receipt.receipt_date}`}> <td>{receipt.receipt_date}</td><td>{branches.find((branch) => String(branch.id) === String(receipt.branch_id))?.name}</td><td>{money(receipt.gross_sales_expected)}</td><td>{receipt.source === 'POS_WITHOUT_RECEIPT' ? 'POS ส่วนเสริม · ยังไม่มีใบรับเงิน' : receipt.status === 'CLOSED' ? 'ใบรับเงินปิดแล้ว' : 'ใบรับเงินยังไม่ปิด'}</td></tr>)}</tbody></table></div> : <>{(filtered.length > 0 || (selectedHrms.length === 0 && selectedManual.length === 0)) && renderItems(filtered)}{selectedHrms.map((item) => <p key={item.stable_key}>แหล่งระบบ: {item.description} · {branches.find((b) => String(b.id) === String(item.branch_id))?.name || ({CENTRAL:'ส่วนกลาง',PRODUCTION:'ผลิต',UNASSIGNED:'ไม่ระบุสาขา'}[item.bucket])} · {money(item.amount)} บาท</p>)}{selectedRecurring.map((item) => <p key={`recurring:${item.id}`}>รายจ่ายประจำ: {item.description} · {money(item.amount)} บาท/เดือน</p>)}{selectedManual.map((item) => <p key={item.id}>กรอกเอง: {item.description} · {money(item.amount)} บาท</p>)}</>}</section>}
      <section className="pnl-todo"><h2>ต้องทำ</h2><h3>รอจัดหมวด ({waiting.length} รายการ, {money(sumPnlRows(waiting))} บาท)</h3><div className="pnl-waiting-toolbar"><label>ค้นหาชื่อร้านหรือรายละเอียด<input type="search" value={waitingSearch} onChange={(event) => {setWaitingSearch(event.target.value); setShowAllWaiting(false);}}/></label><span>แสดง {waitingView.items.length} จาก {waitingView.count} รายการ · ยอดมากไปน้อย</span></div>{renderItems(waitingView.items)}{waitingView.count > 15 && <button aria-expanded={showAllWaiting} onClick={() => setShowAllWaiting(!showAllWaiting)}>{showAllWaiting ? 'แสดง 15 รายการแรก' : `แสดงทั้งหมด (${waitingView.count})`}</button>}<details className="pnl-suggestions"><summary>คำแนะนำย้ายเดือน ({suggestions.length}) · ตรวจบิลก่อนยืนยัน</summary>{renderItems(suggestions)}</details></section>
      {['moved_in', 'moved_out'].map((key) => report[key]?.count > 0 && <section key={key}><h2>{key === 'moved_in' ? 'ย้ายมาจากเดือนอื่น' : 'ย้ายไปเดือนอื่น'} ({report[key].count} รายการ, {money(report[key].amount)} บาท)</h2><p>ยอดรายการเต็มก่อนตัดรายการไม่นับ · เดือนรายงาน {formatPnlMonth(month)}</p>{renderItems(report[key].items)}</section>)}

      <section><h2>ไม่นับเป็นค่าใช้จ่าย · {money(report.excluded_total)} บาท</h2>{renderItems(excluded)}</section>
      <RecurringExpenses key={`${month}:${branchId}`} month={month} report={report} mode={mode} recurring={report.recurring} categories={categories} branches={branches} busy={busy} act={act} send={send} request={request} onLine={setSelected}/>
      <section><h2>รายจ่ายกรอกเอง · {money(report.manual_total)} บาท</h2><p>ถ้าจ่ายเท่ากันทุกเดือน ให้ตั้งเป็นรายจ่ายประจำ</p><div className="pnl-table-scroll"><table><thead><tr><th>รายละเอียด</th><th>หมวด / สาขา</th><th>ยอด</th><th>จัดการ</th></tr></thead><tbody>{report.manual_expenses.map((item) => <tr key={item.id}><td>{item.description}</td><td>{categories.find((row) => row.code === item.category_code)?.name} / {branches.find((row) => row.id === item.branch_id)?.name || 'ส่วนกลาง'}</td><td className={item.amount < 0 ? 'pnl-negative' : ''}>{money(item.amount)}</td><td><button disabled={busy} onClick={() => {setForm({ ...item, branch_id: item.branch_id || '' }); setEditing(item.id);}}>แก้ไข</button><button disabled={busy} onClick={() => act(() => send('DELETE', `/manual-expenses/${item.id}`))}>ลบ</button></td></tr>)}</tbody></table></div>
        <form className="pnl-form" onSubmit={(e) => {e.preventDefault(); act(async () => {await send(editing ? 'PUT' : 'POST', `/manual-expenses${editing ? '/' + editing : ''}`, {...form, month}); setForm(emptyForm()); setEditing(null);});}}>
          <label>หมวด<select required value={form.category_code} onChange={(e) => setForm({...form, category_code:e.target.value})}>{categoryOptions}</select></label><label>สาขา<select value={form.branch_id} onChange={(e) => setForm({...form, branch_id:e.target.value})}>{branchOptions}</select></label><label>รายละเอียด<input required maxLength={300} value={form.description} onChange={(e) => setForm({...form, description:e.target.value})}/></label><label>ยอด (บาท)<input required inputMode="decimal" value={form.amount} onChange={(e) => setForm({...form, amount:e.target.value})}/></label><label>หมายเหตุ<input maxLength={500} value={form.note || ''} onChange={(e) => setForm({...form, note:e.target.value})}/></label><button disabled={busy}>{editing ? 'บันทึกการแก้ไข' : 'ยืนยันเพิ่มรายจ่าย'}</button>{editing && <button type="button" onClick={() => {setEditing(null); setForm(emptyForm());}}>ยกเลิก</button>}
        </form>
        <button disabled={busy} onClick={() => act(async () => { const rows = await request(`/pnl/manual-expenses?${new URLSearchParams({month:previousMonth(month), branch_id:branchId})}`); setCopies(rows); })}>คัดลอกจากเดือนก่อน</button>
        {copies.length > 0 && <div><p>เลือกเติมฟอร์ม แล้วกดยืนยันเพิ่มรายจ่ายเพื่อบันทึก</p>{copies.map((item) => <button key={item.id} onClick={() => {setEditing(null); setForm({...item, branch_id:item.branch_id || ''});}}>{item.description} · {money(item.amount)} บาท</button>)}</div>}
      </section>
      <details><summary>กฎจัดหมวด ({rules.length})</summary>{rules.map((rule) => <p key={rule.id}>{rule.match_field === 'supplier' ? 'ร้าน' : 'วัตถุประสงค์'}: {rule.pattern} · {rule.created_by == null ? 'ระบบ' : `ผู้ใช้ #${rule.created_by}`} → {categories.find((row) => row.code === rule.category_code)?.name} <button disabled={busy} onClick={() => act(() => send('DELETE', `/rules/${rule.id}`))}>ลบกฎ</button></p>)}</details>
      <section aria-label="แหล่งข้อมูล"><h2>แหล่งข้อมูล</h2><details className="pnl-source"><summary><strong>ค่าธรรมเนียมและการตลาดจากใบรับเงินทั้งเดือน · {money(report.cashflow_fee_total || 0)} บาท</strong><span className="pnl-source-status">ใบรับเงินปิดแล้ว</span>{report.cashflow_fee_status?.status === 'partial' && <span role="alert" className="pnl-warning">บางช่องทางยังไม่มีค่าธรรมเนียมที่ยืนยัน · ยอดค่าใช้จ่ายอาจไม่ครบ</span>}</summary><p>อ่านจากใบรับเงินที่ปิดแล้ว · รวมการตลาดที่หักในยอดค่าธรรมเนียมอยู่แล้วครั้งเดียว · ยอดชำระเป็นชุดใช้ส่วนที่จัดสรรให้แต่ละวัน</p><div className="pnl-table-scroll"><table><thead><tr><th>วันที่</th><th>รายการ</th><th>ยอด</th></tr></thead><tbody>{(report.cashflow_expenses || []).map((item) => <tr key={item.stable_key}><td>{formatPnlDate(item.business_date)}</td><td>{item.description}</td><td>{money(item.amount)}</td></tr>)}</tbody></table></div></details><details className="pnl-source"><summary><strong>เงินจ่ายพนักงานจาก HRMS · {money(report.hrms_total || 0)} บาท</strong><span className="pnl-source-status">{report.hrms_status?.status === 'available' ? 'เชื่อม HRMS แล้ว' : 'HRMS ยังไม่พร้อม'}</span>{report.hrms_status?.status === 'not_configured' && <span role="alert" className="pnl-warning">ยังไม่ได้เชื่อม HRMS · ยอดเงินจ่ายพนักงานยังไม่รวมในกำไร</span>}{report.hrms_status?.status === 'unavailable' && <span role="alert" className="pnl-warning">ดึง HRMS ไม่สำเร็จ · ยอดเงินจ่ายพนักงานยังไม่ครบ โปรดลองโหลดใหม่</span>}{report.hrms_status?.status === 'available' && report.hrms_status.payroll_status !== 'locked' && <span className="pnl-warning">รอบเงินเดือนยังไม่ล็อกหรือไม่พบรอบ · ยังไม่นับเงินเดือนสุทธิ</span>}{report.hrms_status?.unmapped_branches?.length > 0 && <span className="pnl-warning">HRMS ยังไม่เชื่อมสาขา: {report.hrms_status.unmapped_branches.join(', ')} · ยอดอยู่ในไม่ระบุสาขา</span>}{mode === 'matched' && report.hrms_total > 0 && <span className="pnl-warning">ยอด HRMS นับเต็มเดือน ไม่เฉลี่ยตามวันที่ข้อมูลครบ · เปลี่ยนเป็นทั้งเดือนเพื่อเทียบเงินจ่ายกับรายรับทั้งเดือน</span>}{report.hrms_total > 0 && report.hrms_possible_overlap_total > 0 && <span role="alert" className="pnl-warning">มีค่าแรงจาก LINE/กรอกเองอีก {money(report.hrms_possible_overlap_total)} บาท · อาจซ้ำกับ HRMS ให้ตรวจรายการก่อนใช้ยอดกำไร</span>}</summary>
        <p>ถือว่าจ่ายครบตามคำยืนยันเจ้าของ · เงินเดือนสุทธิ + เงินต้นเบิกกลางเดือน + ทิปจ่ายแยกที่ปิดรอบแล้ว · ไม่บวกดอกเบี้ยหรือยอดหักคืนซ้ำ</p>
        <p>เงินเดือนลงตามเดือนของรอบ เนื่องจาก HRMS ไม่เก็บวันที่โอนของทั้งรอบ · เงินเบิกลงตามเดือนรับเงินวันที่ 15</p>
        <div className="pnl-table-scroll"><table><thead><tr><th>รายการ</th><th>สาขา</th><th>ยอดจ่าย</th></tr></thead><tbody>{(report.hrms_expenses || []).map((item) => <tr key={item.stable_key}><td>{item.description}</td><td>{branches.find((b) => String(b.id) === String(item.branch_id))?.name || ({CENTRAL:'ส่วนกลาง',PRODUCTION:'ผลิต',UNASSIGNED:'ไม่ระบุสาขา'}[item.bucket])}</td><td>{money(item.amount)}</td></tr>)}</tbody></table></div>
        <p>หากเคยลงเงินเดือนหรือเงินเบิกในบิล LINE หรือรายจ่ายกรอกเอง ให้ตรวจและไม่นับรายการซ้ำก่อนใช้ยอดกำไร · รายการแก้ไขเงินหลังล็อกยังไม่ดึงอัตโนมัติ; ทิปที่ยังเป็นร่างยังไม่นับ</p></details><details className="pnl-source"><summary><strong>แหล่งรายรับที่นำมาคำนวณ · {money(totals.revenue)} บาท</strong><span className="pnl-source-status">ใบรับเงิน + POS ส่วนเสริม</span>{totals.pos_without_receipt_revenue > 0 && <span className="pnl-warning">ยอด POS ส่วนเสริมยังไม่ได้ตรวจปิดใบรับเงิน</span>}{report.pos_revenue_status?.status === 'unavailable' && <span role="alert" className="pnl-warning">ดึงยอด POS ส่วนเสริมไม่ได้ · รายรับและกำไรยังไม่ครบ โปรดลองโหลดใหม่</span>}{report.pos_revenue_status?.unmapped_branch_ids?.length > 0 && <span className="pnl-warning">ยังไม่ได้เชื่อม POS สำหรับ {report.pos_revenue_status.unmapped_branch_ids.map((id) => branches.find((branch) => String(branch.id) === String(id))?.name || id).join(', ')} · วันที่ไม่มีใบรับเงินยังขาดรายรับ</span>}</summary><p>จากใบรับเงิน {money(totals.receipt_revenue)} บาท · จาก POS ที่ยังไม่มีใบรับเงิน {money(totals.pos_without_receipt_revenue)} บาท ({totals.pos_without_receipt_days} วันสาขา)</p><p>ยอด POS ส่วนเสริมยังไม่ได้ตรวจปิดใบรับเงิน เมื่อมีใบรับเงินแล้วระบบจะใช้ยอดในใบรับเงินแทน</p><button className="pnl-link" onClick={() => setSelected('REVENUE')}>ดูวันที่และยอดรายรับ</button></details></section>
    </>}
  </main>;
}
function ExpenseRow({ item, categories, busy, onSave }) {
  const [period, setPeriod] = useState(item.period_month || item.business_date.slice(0, 7));
  const bounds = periodMonthBounds(item.business_date);
  useEffect(() => setPeriod(item.period_month || item.business_date.slice(0, 7)), [item.period_month, item.business_date]);
  const [category, setCategory] = useState(item.category_code || ''); const [rule, setRule] = useState(false);
  useEffect(() => setCategory(item.category_code || ''), [item.category_code]);
  const types = {internal_transfer:'โอนภายใน',loan:'เงินกู้',refund_adjustment:'คืนเงิน',purchase:'ซื้อสินค้า',advance_payment:'สำรองจ่าย',reimbursement:'คืนเงินสำรอง',unknown:'ไม่ระบุ'};
  const [moving, setMoving] = useState(false);
  return <article className="pnl-expense-row" aria-label={`${item.supplier_name || 'ไม่ระบุร้าน'} ${money(item.amount)} บาท`}>
    <div className="pnl-expense-identity" title={`${formatPnlDate(item.business_date)} · ${item.supplier_name || 'ไม่ระบุร้าน'}`}>{formatPnlDate(item.business_date)} · {item.supplier_name || 'ไม่ระบุร้าน'}</div>
    <div className="pnl-expense-description"><span title={item.description}>{item.description}</span><small>{types[item.transaction_type] || 'ไม่ระบุประเภท'} {item.unreviewed && '· ยังไม่ตรวจประเภท'} {item.kind === 'PAYMENT_WITHOUT_BILL' && '· จ่ายโดยไม่มีบิล'} {item.period_month && `· เดือนรับรู้ ${formatPnlMonth(item.period_month)}`}</small></div>
    <div className={`pnl-expense-amount ${item.amount < 0 ? 'pnl-negative' : ''}`}>{money(item.amount)}</div>
    <div className="pnl-expense-category"><select aria-label={`หมวดของ ${item.supplier_name || item.description}`} value={category} onChange={(event) => setCategory(event.target.value)}><option value="">ยังไม่จัดหมวด</option>{categories.map((row) => <option key={row.code} value={row.code}>{row.name}</option>)}</select><button disabled={busy || (rule && !category)} onClick={() => onSave({ category_code: category || null, ...(rule ? {create_rule:'supplier'} : {}) })}>บันทึก</button><label><input type="checkbox" checked={rule} onChange={(event) => setRule(event.target.checked)}/>ใช้กับร้านนี้ทุกครั้ง</label></div>
    <details className="pnl-expense-menu"><summary aria-label={`จัดการรายการ ${item.supplier_name || item.description}`}>⋯</summary><div><button disabled={busy} onClick={() => onSave({excluded:!item.excluded})}>{item.excluded ? 'นับเป็นค่าใช้จ่าย' : 'ไม่นับรายการนี้'}</button><button disabled={busy} onClick={(event) => {setMoving(!moving); event.currentTarget.closest('details').open = false;}}>ย้ายเดือน…</button>{item.source_url && <a href={item.source_url} target="_blank" rel="noreferrer">ดูบิล</a>}{item.period_month && <button disabled={busy} onClick={() => onSave({period_month:null})}>ย้ายกลับ {formatPnlMonth(bounds.max)}</button>}</div></details>
    {item.suggested_period_month && item.suggested_period_month !== item.period_month && <div className="pnl-expense-suggestion"><button className="pnl-period-suggestion" disabled={busy} onClick={() => onSave({period_month:item.suggested_period_month})}>ย้ายไป {formatPnlMonth(item.suggested_period_month)}</button></div>}
    {moving && <div className="pnl-expense-move"><label>เดือนของค่าใช้จ่าย<input type="month" min={bounds.min} max={bounds.max} value={period} disabled={busy} onChange={(event) => setPeriod(event.target.value)}/></label><button disabled={busy || !period || period < bounds.min || period > bounds.max} onClick={() => onSave({period_month:period})}>ยืนยันย้ายเดือน</button><button onClick={() => setMoving(false)}>ยกเลิก</button></div>}
  </article>;
}
